### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

### ISSUE THREAD

**Issue by kMikaZu** [RodneyLeeBrands/UnifiSnipeSync#7]
When I run the `main.py` script, it eventually runs the `ratelimiter.py` script but returns the following error: 

```bash
Traceback (most recent call last):
  File ".../unifi2snipe/build/Mirto Unifi2snipe Sync Manually.app/Contents/Resources/main.py", line 12, in <module>
    from snipe import Snipe
  File ".../unifi2snipe/build/Mirto Unifi2snipe Sync Manually.app/Contents/Resources/snipe.py", line 3, in <module>
    from ratelimiter import RateLimiter
  File ".../unifi2snipe/build/venv/lib/python3.13/site-packages/ratelimiter.py", line 36, in <module>
    class RateLimiter(object):
    ...<94 lines>...
            return self.calls[-1] - self.calls[0]
  File ".../unifi2snipe/build/venv/lib/python3.13/site-packages/ratelimiter.py", line 127, in RateLimiter
    __aexit__ = asyncio.coroutine(__exit__)
                ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```

From what I found, Generator-bases Coroutines are deprecated since Python 3.11. See [this](https://docs.python.org/3.10/library/asyncio-task.html#generator-based-coroutines) info and [this](https://stackoverflow.com/questions/74345065/attributeerror-module-asyncio-has-no-attribute-coroutine-in-python-3-11) thread.

**Comment by kMikaZu** [comment]
Looks like the [ratelimiter](https://github.com/RazerM/ratelimiter) project is EOL... The developer now [recommends](https://github.com/RazerM/ratelimiter/issues/17) rush.

**Comment by kMikaZu** [comment]
@snipe and @karpadiem : Is this project still maintained?

**Comment by snipe** [comment]
@kMikaZu I honestly don't know, I wasn't really a part of it to begin with, I just contributed a little. If @karpadiem wants us to fork it and take it over or what. I completely understand if he doesn't have time to maintain it, and I'm not sure we do either, but we don't really have direct contact with @karpadiem outside of this repo. 

@karpadiem - if you're interested in us taking this project over, email me at snipe@snipe.net or agianotto@grokability.com. And thank you for creating it in the first place! <3

**Comment by kMikaZu** [comment]
Thanks for taking the time to answer on this thread. I think maintaining this project would benefit the splendid Snipe-IT project. And UniFi is a huge vendor, so...

Thanks a lot for considering an update!

**Comment by snipe** [comment]
@kMikaZu For sure, I just prefer to work with the original author of this library (@karpadiem) to see how he'd like to proceed. I agree there is definitely merit in keeping it compatible and functional, just want to make sure we're not stomping on other contributors :)

**Comment by kMikaZu** [comment]
I perfectly understand!

**Comment by snipe** [comment]
Our challenge here is that we don't currently have access to UniFi, so while we can speak Python and know APIs just fine, it's hard for us to test anything we might do. :-/  We'd be happy to PR against this repo, but it would be a blind PR, and we really hate doing those.

**Comment by kMikaZu** [comment]
Do you have UniFi devices at hand? 
I think I can arrange something with a client from me. He has old UniFi stuff laying around and could setup a separate network with controller. I keep you posted.

**Comment by kMikaZu** [comment]
@snipe ? Do you need me to arrange the setup of a test network for you?

**Comment by snipe** [comment]
@kMikaZu - We've forked this over at https://github.com/grokability/UnifiSnipeSync and will hopefully get a chance to take a look soon. (I just got back from vacation, so still trying to get caught up.)

**Comment by jerm** [comment]
This has been fixed over on our adopted fork, FYI

https://github.com/grokability/UnifiSnipeSync

**Comment by kMikaZu** [comment]
I noticed it before I saw this comment! Thanks a lot!
